name: Upload Frontend Files to S3

on: 
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v6
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with: 
        role-to-assume: arn:aws:iam::000363030077:role/s3-github-role
        aws-region: us-east-1

    - name: Upload HTML file to S3
      run: aws s3 cp website/frontend/ s3://banksie.app/ --recursive

    - name: Notify Slack if pipeline fails
      if: failure()
      uses: slackapi/slack-github-action@v2.1.1
      with:
        payload: |
          {
            "text": "🚨 *Upload to S3 Failed*\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nWorkflow: ${{ github.workflow }}\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
